# Generated by Django 4.2.30 on 2026-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display name, e.g. "S&P 500".', max_length=50)),
                ('symbol', models.CharField(help_text='Yahoo Finance ticker symbol, e.g. "^GSPC", "GC=F".', max_length=20, unique=True)),
                ('value_format', models.CharField(choices=[('index', 'Plain number (e.g. 5,123.41)'), ('percent', 'Percent (e.g. 4.42%)'), ('currency', 'Currency (e.g. $113.20)')], default='index', max_length=10)),
                ('change_format', models.CharField(choices=[('percent', 'Percent change (e.g. -0.4%)'), ('bp', 'Basis points (e.g. +3 bp) — for yields')], default='percent', max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Show in the client portal ticker.')),
                ('is_hero_stat', models.BooleanField(default=False, help_text='Also show as one of the 2 stat tiles on the Featured Research hero card.')),
                ('last_price', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('last_change', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('last_change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'market_instruments',
                'ordering': ['display_order', 'label'],
            },
        ),
    ]
