# Generated by Django 4.2.30 on 2026-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_provider', models.CharField(choices=[('openai', 'ChatGPT'), ('anthropic', 'Claude'), ('gemini', 'Gemini')], default='gemini', max_length=20)),
                ('default_report_size', models.CharField(choices=[('short', 'Short note · ~400 words · 2 pages'), ('standard', 'Standard insight · ~900 words · 5 pages'), ('deep', 'Deep dive · ~2000 words · 10 pages')], default='standard', max_length=20)),
                ('temperature', models.FloatField(default=0.4)),
                ('house_style_instructions', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI generation defaults',
                'verbose_name_plural': 'AI generation defaults',
            },
        ),
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'ChatGPT'), ('anthropic', 'Claude'), ('gemini', 'Gemini')], max_length=20, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('default_model', models.CharField(blank=True, max_length=100)),
                ('secondary_field_value', models.CharField(blank=True, max_length=255)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
