# Generated by Django 4.2.30 on 2026-07-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('purple', 'Purple'), ('gray', 'Gray'), ('green', 'Green'), ('amber', 'Amber')], default='blue', max_length=10)),
                ('is_system', models.BooleanField(default=False, help_text='Built-in role — cannot be deleted.')),
                ('is_internal', models.BooleanField(default=True, help_text='Internal GCIO staff role with admin console access, as opposed to a client-facing role.')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Create, edit, and deactivate user accounts.')),
                ('can_manage_roles', models.BooleanField(default=False, help_text='Create and edit roles and their permissions.')),
                ('can_manage_organizations', models.BooleanField(default=False, help_text='Create and edit client organisations.')),
                ('can_manage_content', models.BooleanField(default=False, help_text='Upload and manage articles, PDFs, presentations.')),
                ('can_view_all_organizations', models.BooleanField(default=False, help_text='See content for every organisation, not just the ones assigned to this user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
