# Generated by Django 4.2.30 on 2026-08-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_seed_system_roles'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
    ]
