# Generated by Django 4.2.30 on 2026-08-01 17:07

from django.db import migrations, models


def backfill_new_permissions(apps, schema_editor):
    Role = apps.get_model('roles', 'Role')
    for role in Role.objects.all():
        role.can_manage_taxonomy = role.can_manage_content
        role.can_view_logs = role.can_manage_users
        role.save(update_fields=['can_manage_taxonomy', 'can_view_logs'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_alter_role_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_taxonomy',
            field=models.BooleanField(default=False, help_text='Manage authors and classification taxonomy (asset classes, countries, publication types, tags).'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_logs',
            field=models.BooleanField(default=False, help_text='View the admin actions log.'),
        ),
        migrations.RunPython(backfill_new_permissions, noop_reverse),
    ]
