# Generated by Django 4.2.30 on 2026-08-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_role_can_manage_taxonomy_role_can_view_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_market_data',
            field=models.BooleanField(default=False, help_text='Manage market data instruments and refresh prices from Yahoo Finance.'),
        ),
    ]
