# Generated by Django 4.2.30 on 2026-07-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, help_text='Byline title shown on authored reports, e.g. "Head of Research".', max_length=150),
        ),
    ]
