# Generated by Django 4.2.30 on 2026-08-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_organizations_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_author',
            field=models.BooleanField(default=True, help_text='Whether this user is featured in the Taxonomy authors list.'),
        ),
    ]
