# Generated by Django 4.2.30 on 2026-07-25 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '0003_assetclass_is_active_countryregion_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('asset_classes', models.ManyToManyField(blank=True, related_name='reports', to='taxonomy.assetclass')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('countries_regions', models.ManyToManyField(blank=True, related_name='reports', to='taxonomy.countryregion')),
                ('publication_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='taxonomy.publicationtype')),
                ('tags', models.ManyToManyField(blank=True, related_name='reports', to='taxonomy.reporttag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
