# Generated by Django 4.2.30 on 2026-07-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='access_level',
            field=models.CharField(choices=[('all', 'All users'), ('selected', 'Selected organisations')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text article'), ('pdf', 'PDF'), ('presentation', 'Presentation')], default='text', max_length=15),
        ),
        migrations.AddField(
            model_name='report',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='reports/uploads/'),
        ),
        migrations.AddField(
            model_name='report',
            name='page_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='report',
            name='visible_organizations',
            field=models.ManyToManyField(blank=True, related_name='visible_reports', to='organizations.organization'),
        ),
    ]
