# Generated by Django 4.2.30 on 2026-08-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_access_level_report_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='reports',
        ),
    ]
