# Generated by Django 4.2.30 on 2026-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in the Featured Research section on the client portal home page.'),
        ),
    ]
