# Generated by Django 4.2.30 on 2026-08-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('text', 'Article'), ('pdf', 'PDF'), ('presentation', 'Presentation')], default='text', max_length=15),
        ),
    ]
