# Generated by Django 4.2.30 on 2026-07-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetclass',
            table='taxonomy_asset_class',
        ),
        migrations.AlterModelTable(
            name='countryregion',
            table='taxonomy_country_region',
        ),
        migrations.AlterModelTable(
            name='publicationtype',
            table='taxonomy_publication_type',
        ),
        migrations.AlterModelTable(
            name='reporttag',
            table='taxonomy_report_tag',
        ),
    ]
