# Generated by Django 4.2.30 on 2026-07-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_alter_assetclass_table_alter_countryregion_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countryregion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publicationtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reporttag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
