# Generated by Django 4.2.30 on 2026-08-08 12:55

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    for model_name in ('AssetClass', 'CountryRegion', 'PublicationType', 'ReportTag'):
        model = apps.get_model('taxonomy', model_name)
        seen = set(model.objects.exclude(slug='').values_list('slug', flat=True))
        for term in model.objects.filter(slug=''):
            base_slug = slugify(term.name) or 'term'
            slug = base_slug
            suffix = 2
            while slug in seen:
                slug = f'{base_slug}-{suffix}'
                suffix += 1
            seen.add(slug)
            term.slug = slug
            term.save(update_fields=['slug'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_assetclass_is_active_countryregion_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetclass',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=170),
        ),
        migrations.AddField(
            model_name='countryregion',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=170),
        ),
        migrations.AddField(
            model_name='publicationtype',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=170),
        ),
        migrations.AddField(
            model_name='reporttag',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=170),
        ),
        migrations.RunPython(populate_slugs, noop_reverse),
        migrations.AlterField(
            model_name='assetclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
        migrations.AlterField(
            model_name='countryregion',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
        migrations.AlterField(
            model_name='publicationtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
        migrations.AlterField(
            model_name='reporttag',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
    ]
