# Generated by Django 4.2.30 on 2026-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_add_slug_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetclass',
            name='show_on_home',
            field=models.BooleanField(default=True, help_text='Show in the "Research by Asset Class" section on the client home page.'),
        ),
        migrations.AddField(
            model_name='publicationtype',
            name='show_on_home',
            field=models.BooleanField(default=True, help_text='Show in the "Regular Publications" section on the client home page.'),
        ),
    ]
