# Generated by Django 4.2.30 on 2026-08-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_assetclass_show_on_home_publicationtype_show_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationtype',
            name='cadence_label',
            field=models.CharField(blank=True, help_text='How often it publishes, e.g. "Every trading day". Optional.', max_length=100),
        ),
        migrations.AddField(
            model_name='publicationtype',
            name='description',
            field=models.TextField(blank=True, help_text='Shown on the series page header. Optional.'),
        ),
        migrations.AddField(
            model_name='publicationtype',
            name='series_name',
            field=models.CharField(blank=True, help_text='Display title for the series page, e.g. "The GCIO Daily". Defaults to the name above if left blank.', max_length=150),
        ),
    ]
