# Generated by Django 4.2.30 on 2026-08-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_assetclass_is_active_countryregion_is_active_and_more'),
        ('organizations', '0002_organization_country_organization_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='taxonomy.countryregion'),
        ),
    ]
