# Generated by Django 4.2.30 on 2026-08-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
    ]
